# Generated by Django 6.0.2 on 2026-03-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_shipping_address_order_shipping_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('bKash', 'bKash'), ('Card', 'Card')], max_length=50),
        ),
    ]
